Repository MacRoberto/travel-segundo-parcial, pull requests merged in 2024-11, with the labels that each got.

#19 Our service
  css/travel.css
  img/Rectangle 3.svg
  img/Ticket.png
  img/Ticketotrave.png
  img/Vector.png
  img/carbon_hotel.png
  img/cil_paper-plane.png
  travel.html
Labels: enhancement, help wanted, question

#21 Se resolvió el error de header.
  css/travel.css
Labels: bug

#23 Our service
  travel.html
Labels: bug

#24 Best Service
  css/travel.css
  img/calendar_icon.svg
  img/history_icon.svg
  img/map_icon.svg
  img/mapa_mundi.svg
  img/stadistics_icon.svg
  travel.html
Labels: enhancement

#25 Popular_Destination
  css/travel.css
  img/go-click.svg
  img/indonesia.png
  img/new.png
  img/popular-map.png
  img/thailand.png
  travel.html
Labels: enhancement

#26 Se realizo el Package
  css/travel.css
  img/china.svg
  img/isla.svg
  img/location_mark.svg
  img/mountains.svg
  travel.html
Labels: enhancement

#29 Correccion de errores,
  .vscode/settings.json
  css/travel.css
  img/china.svg
  img/isla.jpg
  img/isla.svg
  img/japan.jpg
  img/mountains.jpg
  img/mountains.svg
  travel.html
Labels: enhancement

#31 Reinicio-De-Book
  css/travel.css
  img/GroupBook1.png
  img/GroupBook2.png
  img/GroupBook3.png
  img/UnaDoñaFelizOAlgoAsi.png
  travel.html
Labels: enhancement

#35 Maquetado Book y Pequeña modificacion a Our service
  css/travel.css
  travel.html
Labels: enhancement

#36 People Say About Us
  css/travel.css
  img/people_opinions.svg
  travel.html
Labels: enhancement

#37 Maquetado-Suscribe
  css/travel.css
  img/mail.png
  img/suscribe-fondo.svg
  travel.html
Labels: enhancement

#38 Maquetado-de-Footer
  css/travel.css
  img/Google Play.jpg
  img/Play Store.jpg
  img/facebook.jpg
  img/insta.jpg
  img/logo-black.svg
  img/twiter.jpg
  travel.html
Labels: enhancement
